### ISSUE TITLE
Investigate adding a version number to `software` field of warcinfo

### ISSUE THREAD

**Issue by NGTmeaty** [CorentinB/Zeno#5]
Maybe the current git hash if possible? If not, hardcoded version number?

I guess we'll also need to pass this information to `warc`. `warc` should also pass its own version number.

**Comment by CorentinB** [comment]
Yep, good idea.
Related: https://github.com/CorentinB/Zeno/issues/10

**Comment by CorentinB** [comment]
Done in https://github.com/CorentinB/Zeno/pull/28
